//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabalhoBD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ImobiliariaBDEntities : DbContext
    {
        public ImobiliariaBDEntities()
            : base("name=ImobiliariaBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tabela_Bairro> Tabela_Bairro { get; set; }
        public virtual DbSet<Tabela_Cidade> Tabela_Cidade { get; set; }
        public virtual DbSet<Tabela_Construcao> Tabela_Construcao { get; set; }
        public virtual DbSet<Tabela_Estado> Tabela_Estado { get; set; }
        public virtual DbSet<Tabela_Imovel> Tabela_Imovel { get; set; }
    }
}
