//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabalhoBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tabela_Estado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tabela_Estado()
        {
            this.Tabela_Cidade = new HashSet<Tabela_Cidade>();
        }
    
        public int id_estado { get; set; }
        public string nome_estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tabela_Cidade> Tabela_Cidade { get; set; }
    }
}
