//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabalhoBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tabela_Construcao
    {
        public int id_construcao { get; set; }
        public Nullable<int> ano { get; set; }
        public int id_imovel { get; set; }
    
        public virtual Tabela_Imovel Tabela_Imovel { get; set; }
    }
}
