//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabalhoBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tabela_Bairro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tabela_Bairro()
        {
            this.Tabela_Imovel = new HashSet<Tabela_Imovel>();
        }
    
        public int id_bairro { get; set; }
        public string nome_bairro { get; set; }
        public int cep { get; set; }
        public Nullable<int> id_cidade { get; set; }
    
        public virtual Tabela_Cidade Tabela_Cidade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tabela_Imovel> Tabela_Imovel { get; set; }
    }
}
