//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabalhoBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tabela_Imovel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tabela_Imovel()
        {
            this.Tabela_Construcao = new HashSet<Tabela_Construcao>();
        }
    
        public int id_imovel { get; set; }
        public string categoria { get; set; }
        public string status { get; set; }
        public string faixa_iptu { get; set; }
        public string faixa_condominio { get; set; }
        public bool flg_planta { get; set; }
        public bool flg_dependencia { get; set; }
        public bool flg_sacada { get; set; }
        public bool flg_protaria { get; set; }
        public bool flg_elevador { get; set; }
        public string churrasqueira { get; set; }
        public string faixa_dormitorios { get; set; }
        public string faixa_suites { get; set; }
        public string faixa_banheiros { get; set; }
        public string faixa_vagas { get; set; }
        public string faixa_venda { get; set; }
        public string faixa_aluguel { get; set; }
        public Nullable<int> id_bairro { get; set; }
    
        public virtual Tabela_Bairro Tabela_Bairro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tabela_Construcao> Tabela_Construcao { get; set; }
    }
}
