//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabalhoBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tabela_Cidade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tabela_Cidade()
        {
            this.Tabela_Bairro = new HashSet<Tabela_Bairro>();
        }
    
        public int id_cidade { get; set; }
        public string nome_cidade { get; set; }
        public Nullable<int> id_estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tabela_Bairro> Tabela_Bairro { get; set; }
        public virtual Tabela_Estado Tabela_Estado { get; set; }
    }
}
